
-- ERIC AGYEMANG
-- IT 478 ADVANCED DATABASE MANAGEMENT
-- LAB 9

drop Table CH10_SUBJECTS;
drop Table CH10_SUPPLIERS;

SET ECHO ON;
--1. a. Use SQL to create the tables ch10_suppliers and ch10_subjects. Once created, the two tables should have the same column names, null? and type listed below. 
--In addition, SUBJECT_ID, SUBJECT_NAME and SUPPLIER_ID should all be created with the UNIQUE constraint. 
CREATE TABLE ch10_subjects(
SUBJECT_ID NUMBER NOT NULL UNIQUE,
SUBJECT_NAME VARCHAR(30) NOT NULL UNIQUE,
DESCRIPTION VARCHAR2(4000)
);

CREATE TABLE ch10_suppliers(
SUPPLIER_ID NUMBER(10) NOT NULL unique,  
SUPPLIER_NAME VARCHAR2(50) NOT NULL,  
ADDRESS VARCHAR2(50), 
CITY VARCHAR2(50), 
STATE VARCHAR2(25), 
ZIP_CODE VARCHAR2(10) 
);

--b. Run DESC (describe) to show that the tables were created correctly.
DESC ch10_suppliers;
DESC ch10_subjects; 

--2. The DICTIONARY table has two columns TABLE_NAME and COMMENTS.
  --a. Find the TABLE_NAME and COMMENTS of all tables listed in the DICTIONARY table that contain USER_TAB in the table name. (use LIKE) (SHOULD GET 20 ROWS)
COLUMN TABLE_NAME FORMAT A25
COLUMN COMMENTS FORMAT A70 WORD_WRAPPED
SELECT * FROM DICTIONARY WHERE table_name LIKE'%USER_TAB%'; 

  --b. Find the TABLE_NAME and COMMENTS of all tables listed in the DICTIONARY table that contain CONSTRAINT in the table name. (use LIKE) (SHOULD GET 4 ROWS)
COLUMN TABLE_NAME FORMAT A25
COLUMN COMMENTS FORMAT A70 WORD_WRAPPED
SELECT * FROM DICTIONARY WHERE table_name LIKE '%CONSTRAINT%'; 

  --c. Find the TABLE_NAME and COMMENTS of all tables listed in the DICTIONARY table that contain USER_IND in the table name. (use LIKE) (SHOULD GET 11 ROWS)
COLUMN TABLE_NAME FORMAT A25
COLUMN COMMENTS FORMAT A70 WORD_WRAPPED
SELECT * FROM DICTIONARY WHERE table_name LIKE '%USER_IND%'; 

--3. We are going to explore the contents of 3 of the tables you found in 2 (a, b & c). 
  --a. Find TABLE_NAME, OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, LAST_CHANGE and SEARCH_CONDITION of the tables you created today FROM the table ALL_CONSTRAINTS. 
  --HINT: use WHERE table_name LIKE 'CH10_%'
COLUMN OWNER FORMAT A20
COLUMN CONSTRAINT_NAME FORMAT A20
COLUMN CONSTRAINT_TYPE FORMAT A20
COLUMN LAST_CHANGE FORMAT A20
COLUMN SEARCH_CONDITION FORMAT A30 


SELECT TABLE_NAME, OWNER,CONSTRAINT_NAME,CONSTRAINT_TYPE,LAST_CHANGE,SEARCH_CONDITION
FROM ALL_CONSTRAINTS
WHERE TABLE_NAME LIKE'%CH10_%'
ORDER BY OWNER;


 --b. Find TABLE_NAME, COLUMN_NAME, DATA_TYPE of the tables you created today FROM the table USER_TAB_COLS. See hint above.


COLUMN TABLE_NAME FORMAT A20
COLUMN COLUMN_NAME FORMAT A20
COLUMN DATA_TYPE FORMAT A20
SELECT TABLE_NAME, COLUMN_NAME,DATA_TYPE FROM ALL_TAB_COLS
WHERE TABLE_NAME LIKE 'CH10_%'
ORDER BY OWNER;


--3C. Find INDEX_NAME, TABLE_NAME, COLUMN_NAME and DESCEND of the tables you created today FROM the table USER_IND_COLUMNS. See hint above.
COLUMN INDEX_NAME FORMAT A20
COLUMN TABLE_NAME FORMAT A20
COLUMN COLUMN_NAME FORMAT A20
COLUMN DESCEND FORMAT A20

SELECT 
INDEX_NAME,
TABLE_NAME,
COLUMN_NAME,
DESCEND
FROM USER_IND_COLUMNS
WHERE TABLE_NAME LIKE 'CH10_%'
order by table_name;
























