DROP TABLE UBOATS;
DROP TABLE SHIPS;
DROP TABLE ATTACKS;

CREATE TABLE UBOATS
   (	UBOAT VARCHAR2(10) PRIMARY KEY,
  COMMANDER VARCHAR2(40)
   );
   
   CREATE TABLE SHIPS
   (	SID  VARCHAR2(10) PRIMARY KEY, 
	SHIP VARCHAR2(40) NOT NULL, 
	TONS NUMBER, 
  NAT VARCHAR2(2)
   );
   
 CREATE TABLE ATTACKS
   ( DAY DATE,
     UBOAT VARCHAR2(10) ,	
     SID  VARCHAR2(10) 
   );
   

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('1', 'HMS MALAYA', 31100.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('4', 'HMS BARHAM', 31100.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('14', 'HMS LCE-14', 10.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('16', 'HMS EDINBURGH', 11500.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('19', 'HMS BIRMINGHAM', 9100.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('28', 'HMS NELSON', 33950.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('35', 'HMS BELFAST', 11500.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('43', 'HMS PHOEBE', 5450.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('50', 'HMS COURAGEOUS', 22500.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('58', 'HMS FIJI', 8000.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('59', 'HMS NEWFOUNDLAND', 8800.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('71', 'HMS GALATEA', 5220.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('74', 'HMS HERMIONE', 5450.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('93', 'HMS NAIAD', 5450.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('94', 'HMS EAGLE', 22600.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('97', 'HMS PENELOPE', 5270.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('102', 'HMS LCT-102', 450.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('119', 'HMS LCT-119', 450.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('305', 'HMS LST-305', 1625.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('324', 'HMS LST-324', 1625.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('339', 'HMS MTB-339', 32.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('342', 'HMS MTB-342', 32.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('362', 'HMS LST-362', 1625.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('404', 'HMS LST-404', 1625.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('418', 'HMS LST-418', 1625.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('508', 'HMS LCM-508', 52.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('509', 'HMS LCM-509', 52.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('519', 'HMS LCM-519', 52.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('522', 'HMS LCM-522', 52.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('523', 'HMS LCM-523 ', 52.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('532', 'HMS LCM-532 ', 52.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('537', 'HMS LCM-537 ', 52.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('547', 'HMS LCM-547 ', 52.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('553', 'HMS LCT-553', 611.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('615', 'HMS P-615', 683.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('620', 'HMS LCM-620 ', 52.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('752', 'HMS LCV-752 ', 10.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('754', 'HMS LCV-754 ', 10.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('1003', 'HMS ML-1003 ', 46.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('1037', 'HMS ML-1037 ', 46.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('1074', 'HMS LCT-1074', 611.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('1090', 'HMNZS ML-1090 ', 46.0, 'NZ');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('1123', 'HMS LCM-1123 ', 52.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('1129', 'HMS LCM-1129 ', 52.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('2006', 'HMS LCT-2006 ', 291.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('2190', 'HMS LCT-2190 ', 291.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('2192', 'HMS LCT-2192 ', 291.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('2239', 'HMS LCT-2239 ', 291.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('2267', 'HMS LCT-2267 ', 291.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('2281', 'HMS LCT-2281 ', 291.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('2284', 'HMS LCT-2284 ', 291.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('2335', 'HMS LCT-2335 ', 291.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('2341', 'HMS LCT-2341 ', 291.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('2344', 'HMS LCT-2344 ', 291.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('2398', 'HMS LCT-2398 ', 291.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('2480', 'HMS LCT-2480 ', 291.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('18A18', 'HMS TLC-18', 372.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('2A2', 'HMS TLC-2', 372.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('7A7', 'HMS TLC-7', 372.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('FY107', 'HMS STELLA CAPELLA', 507.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K416', 'HMS HURST CASTLE', 1010.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K696', 'HMS DENBIGH CASTLE', 1060.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('FY214', 'HMS KINGSTON CEYLONITE (', 448.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('FY250', 'HMS NOTTS COUNTY', 541.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('I81', 'HMCS ST. CROIX', 1190.0, 'CA');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('D10', 'HMS AUDACITY', 11000.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('D14', 'HMS AVENGER', 13785.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('D25', 'HMS WARWICK', 1100.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('D30', 'HMS WHIRLWIND', 1100.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('D48', 'HMS THANE', 11400.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('D57', 'HMS FIDELITY', 2456.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('D72', 'HMS VETERAN', 1120.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('D77', 'HMS NABOB', 11420.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('D93', 'HMS DUNEDIN', 4850.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K122', 'HMS FLEUR DE LYS', 925.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('FY127', 'HMS LOCH DOON', 534.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('F104', 'HMS MANISTEE', 5360.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('F105', 'HMS ARIGUANI', 6746.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('F18', 'HMS CHESHIRE', 10552.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('F20', 'HMS HECLA', 10850.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('F25', 'HMS MEDWAY', 14650.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('F28', 'HMS AURANIA', 13984.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('F29', 'HMS WORCESTERSHIRE', 11402.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('F30', 'HMS FORFAR', 16402.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('F34', 'HMS JAGUAR', 1690.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('F35', 'HMS RAJPUTANA', 16644.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('F50', 'HMS KIMBERLEY', 1690.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('F51', 'HMS LAURENTIC', 18724.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('F56', 'HMS TRANSYLVANIA', 16923.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('F77', 'HMS CAMITO', 6833.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('F94', 'HMS SALOPIAN', 10549.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('FY332', 'HMS SOUTHERN FLOWER', 328.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('FY101', 'HMS ALOUETTE', 520.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('FY141', 'HMS BEDFORDSHIRE', 913.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('FY204', 'HMS ELLESMERE', 580.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('G03', 'HMS COSSACK', 1870.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('G23', 'HMS MAHRATTA', 1920.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('G26', 'HMS MATABELE', 1870.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('G30', 'HMS PARTRIDGE', 1540.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('G33', 'HMS SOMALI', 1870.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('G35', 'HMS MARNE', 1920.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('G39', 'HMS OBDURATE', 1540.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('G44', 'HMS MARTIN', 1920.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('G45', 'HMS QUAIL', 1705.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('G63', 'HMS GURKHA', 1920.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('G93', 'HMS PORCUPINE', 1540.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('G99', 'HMS LAFOREY', 1935.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('H02', 'HMS EXMOUTH', 1475.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('H06', 'HMS HURRICANE', 1340.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('H16', 'HMS DARING', 1375.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('H19', 'HMS HARVESTER', 1340.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('H46', 'HMS BELMONT', 1190.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('H60', 'HMCS OTTAWA', 1375.0, 'CA');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('H64', 'HMS BEVERLEY', 1190.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('H79', 'HMS FIREDRAKE', 1350.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('H81', 'HMS BROADWATER', 1190.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('H89', 'HMS GRAFTON', 1350.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('F160', 'HMS EMPIRE HALBERD', 7177.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('X02', 'HMS CAPE HOWE', 4443.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('I73', 'HMS STANLEY', 1190.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('W25', 'HMS ST. ISSEY', 810.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('J136', 'HMS MAALÃƒËœY', 249.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('J174', 'HMCS CLAYOQUOT', 672.0, 'CA');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('J194', 'HMS HYTHE', 656.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('J217', 'HMS LOYALTY', 850.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('J24', 'HMS HEBE', 835.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('J272', 'HMCS ESQUIMALT', 590.0, 'CA');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('J52', 'HMCS GUYSBOROUGH', 672.0, 'CA');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('J93', 'HMS LEDA', 835.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K103', 'HMCS ALBERNI', 925.0, 'CA');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K115', 'HMCS LEVIS', 925.0, 'CA');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K136', 'HMCS SHAWINIGAN', 900.0, 'CA');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K137', 'HMS PINK', 925.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K173', 'HMCS WEYBURN', 925.0, 'CA');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K190', 'HMS VERVAIN', 925.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K198', 'HMCS SPIKENARD', 925.0, 'CA');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K227', 'HMS ITCHEN', 1370.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K234', 'HMCS REGINA', 925.0, 'CA');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K244', 'HMCS CHARLOTTETOWN', 900.0, 'CA');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K250', 'HMS TWEED', 1370.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K259', 'HMS LAGAN', 1370.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K261', 'HMS MOURNE ', 1370.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K299', 'HMS CUCKMERE', 1300.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K313', 'HMS BLACKWOOD', 1085.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K317', 'HMCS CHEBOGUE ', 1370.0, 'CA');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K329', 'HMCS VALLEYFIELD ', 1445.0, 'CA');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K34', 'HMS GLADIOLUS', 925.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K368', 'HMCS TRENTONIAN', 980.0, 'CA');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K458', 'HMCS TEME', 1370.0, 'CA');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K462', 'HMS AFFLECK', 1085.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K466', 'HMS BICKERTON', 1300.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K469', 'HMS BULLEN', 1300.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K47', 'HMS POLYANTHUS', 925.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K470', 'HMS CAPEL', 1085.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K476', 'HMS GOULD', 1192.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K479', 'HMS GOODALL', 1150.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K480', 'HMS GOODSON', 1300.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K49', 'HMS CROCUS', 925.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K554', 'HMS REDMILL', 1300.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K56', 'HMS ASPHODEL', 1015.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K568', 'HMS MANNERS', 1300.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K569', 'HMS MOUNSEY', 1150.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K580', 'HMS WHITAKER', 1300.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K63', 'HMS PICOTEE', 925.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K673', 'HMCS MAGOG', 1370.0, 'CA');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K80', 'HMS BLUEBELL', 925.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K86', 'HMS ARBUTUS', 925.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K97', 'HMS SALVIA', 925.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('K98', 'HMS ZINNIA', 900.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('L108', 'HMS PUCKERIDGE', 1050.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('L162', 'HMS LCI-162', 246.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('L28', 'HMS PENZANCE', 1025.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('L44', 'HMAS PARRAMATTA ', 1060.0, 'AU');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('L47', 'HMS BLEAN', 1087.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('L56', 'HMS HOLCOMBE', 1087.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('L77', 'HMS GROVE', 1050.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('L84', 'HMS DUNDEE', 1060.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('L85', 'HMS HEYTHROP', 1050.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('L96', 'HMS TYNEDALE', 1000.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('L99', 'HMS LCI-99', 246.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('M70', 'HMS MANXMAN', 2650.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('M84', 'HMS WELSHMAN', 2650.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('N24', 'HMS THISTLE', 1090.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('N69', 'HMS SPEARFISH)', 670.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('OAK08', 'HMS ROYAL OAK', 29150.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('M47', 'HMS SOUTHERN PRINCE', 10917.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('406', 'HMS NORTHERN PRINCESS', 655.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('R08', 'HMS HARDY', 1810.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('R62', 'HMS CASSANDRA', 1710.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('458', 'HMS NORTHERN ROVER', 655.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('91', 'HMS ARK ROYAL', 22600.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('T137', 'HMS LAERTES', 545.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('T169', 'HMS JURA', 545.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('T204', 'HMS ORFASY', 545.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('T218', 'HMS BIRDLIP', 750.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('T223', 'HMS BREDON', 750.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('T367', 'HMS GANILLY', 545.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('T60', 'HMS GNAT', 625.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('U05', 'HMS CHANTICLEER', 1350.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('U08', 'HMS WOODPECKER', 1300.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('U11', 'HMS LARK', 1350.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('U62', 'HMS LAPWING', 1350.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('U81', 'HMS STORK', 1190.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('U87', 'HMS KITE', 1350.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('X39', 'HMS WILLAMETTE VALLEY', 4724.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('FY1601', 'HMS EBOR  WYKE', 348.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('Y87', 'HMS CULVER', 1546.0, 'BR');

INSERT INTO SHIPS (SID, SHIP, TONS, NAT) 
VALUES ('Z05', 'HMS BAYONET', 605.0, 'BR');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-201', 'ADALBERT SCHNEE');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-155', 'ADOLF CORNELIUS PIENING');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-1223', 'ALBERT KNEIP');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-68', 'ALBERT LAUZEMIS');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-161', 'ALBRECHT ACHILLES');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-617', 'ALBRECHT BRANDI');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-510', 'ALFRED EICK');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-454', 'BURCKHARD HACKLÃƒâ€žNDER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-365', 'DIETHER TODENHAGEN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-574', 'DIETRICH GENGELBACH');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-51', 'DIETRICH KNORR');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-548', 'EBERHARD ZIMMERMANN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-868', 'EDUARD TURRE');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-453', 'EGON REINER FREIHERR VON SCHLIPPENBACH');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-74', 'EITEL-FRIEDRICH KENTRAT');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-988', 'ERICH DOBBERSTEIN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-775', 'ERICH TASCHENMACHER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-126', 'ERNST BAUER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-268', 'ERNST HEYDEMANN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-101', 'ERNST MENGERSEN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-407', 'ERNST-ULRICH BRÃƒÅ“LLER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-205', 'FRANZ-GEORG RESCHKE');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-1227', 'FRIEDRICH ALTMEIER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-757', 'FRIEDRICH DEETZ');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-81', 'FRIEDRICH GUGGENBERGER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-66', 'FRIEDRICH MARKWORTH');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-1228', 'FRIEDRICH-WILHELM MARIENFELD');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-21', 'FRITZ FRAUENHEIM');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-30', 'FRITZ-JULIUS LEMP');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-652', 'GEORG-WERNER FRAATZ');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-593', 'GERD KELBLING');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-751', 'GERHARD BIGALK');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-486', 'GERHARD MEYER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-741', 'GERHARD PALMGREN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-107', 'GÃƒÅ“NTER HESSLER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-596', 'GUNTER JAHN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-28', 'GÃƒÅ“NTER KUHNKE');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-295', 'GÃƒÅ“NTER WIEBOLDT');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-558', 'GÃƒÅ“NTHER KRECH');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-47', 'GÃƒÅ“NTHER PRIEN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-214', 'GÃƒÅ“NTHER REEDER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-436', 'GÃƒÅ“NTHER SEIBICKE');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-413', 'GUSTAV POEL');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-409', 'HANNS-FERDINAND MASSMANN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-992', 'HANS FALKE');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-559', 'HANS HEIDTMANN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-32', 'HANS JENISCH');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-62', 'HANS-BERNHARD MICHALOWSKI');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-331', 'HANS-DIEDRICH FREIHERR VON TIESENHAUSEN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-190', 'HANS-ERWIN REITH');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-711', 'HANS-GÃƒÅ“NTHER LANGE');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-221', 'HANS-HARTWIG TROJER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-1022', 'HANS-JOACHIM ERNST');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-480', 'HANS-JOACHIM FÃƒâ€“RSTER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-1105', 'HANS-JOACHIM SCHWARZ');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-483', 'HANS-JOACHIM VON MORSTEIN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-354', 'HANS-JÃƒÅ“RGEN STHAMER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-764', 'HANSKURT VON BREMEN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-4', 'HANS-PETER HINSCH');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-83', 'HANS-WERNER KRAUS');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-59', 'HARALD JÃƒÅ“RST');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-482', 'HARTMUT GRAF VON MATUSCHKA');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-48', 'HEINRICH BLEICHRODT');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-547', 'HEINRICH NIEMEYER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-77', 'HEINRICH SCHONDER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-105', 'HEINRICH SCHUCH');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-1051', 'HEINRICH VON HOLLEBEN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-136', 'HEINRICH ZIMMERMANN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-703', 'HEINZ BIELFELD');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-744', 'HEINZ BLISCHKE');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-390', 'HEINZ GEISSLER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-984', 'HEINZ SIEDER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-91', 'HEINZ WALKERLING');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-372', 'HEINZ-JOACHIM NEUMANN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-73', 'HELMUT ROSENBAUM');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-75', 'HELMUTH RINGELMANN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-666', 'HERBERT ENGEL');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-206', 'HERBERT OPITZ');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-527', 'HERBERT UHLIG');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-137', 'HERBERT WOHLFARTH');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-315', 'HERBERT ZOLLER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-432', 'HERMANN ECKHARDT');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-133', 'HERMANN HESSE');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-701', 'HORST DEGEN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-410', 'HORST-ARNO FENSKI');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-990', 'HUBERT NORDHEIMER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-278', 'JOACHIM FRANZE');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-568', 'JOACHIM PREUSS');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-124', 'JOHANN MOHR');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-31', 'JOHANNES HABEKOST');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-979', 'JOHANNES MEERMEIER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-375', 'JÃƒÅ“RGEN KÃƒâ€“NENKAMP');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-1172', 'JÃƒÅ“RGEN KUHLMANN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-106', 'JÃƒÅ“RGEN OESTEN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-211', 'KARL HAUSE');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-553', 'KARL THURMANN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-22', 'KARL-HEINRICH JENISCH');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-667', 'KARL-HEINZ LANGE');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-1276', 'KARL-HEINZ WENDT');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-563', 'KLAUS HEINRICH BARGSTEN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-521', 'KLAUS HEINRICH BARGSTEN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-806', 'KLAUS HORNBOSTEL');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-552', 'KLAUS POPP');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-108', 'KLAUS SCHOLTZ');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-360', 'KLAUS-HELMUTH BECKER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-443', 'KONSTANTIN VON PUTTKAMER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-415', 'KURT NEIDE');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-456', 'MAX-MARTIN TEICHERT');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-952', 'OSKAR CURIO');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-56', 'OTTO HARMS');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-99', 'OTTO KRETSCHMER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-23', 'OTTO KRETSCHMER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-29', 'OTTO SCHUHART');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-404', 'OTTO VON BÃƒÅ“LOW');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-968', 'OTTO WESTPHALEN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-557', 'OTTOKAR ARNOLD PAULSSEN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-517', 'PAUL HARTWIG');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-230', 'PAUL SIEGMANN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-270', 'PAUL-FRIEDRICH OTTO');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-223', 'PETER GERLACH');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-333', 'PETER-ERICH CREMER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-602', 'PHILIPP SCHÃƒÅ“LER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-123', 'REINHARD HARDEGEN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-564', 'REINHARD SUHREN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-218', 'RICHARD BECKER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-98', 'ROBERT GYSAE');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-358', 'ROLF MANKE');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-608', 'ROLF STRUCKMEIER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-405', 'ROLF-HEINRICH HOPMAN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-305', 'RUDOLF BAHR');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-1004', 'RUDOLF HINZ');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-616', 'SIEGFRIED KOITSCHKA');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-188', 'SIEGFRIED LÃƒÅ“DDEN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-82', 'SIEGFRIED ROLLMANN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-435', 'SIEGFRIED STRELOW');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-1203', 'SIGURD SEEGER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-97', 'UDO HEILMANN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-587', 'ULRICH BORCHERDT');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-624', 'ULRICH GRAF VON SODEN-FRAUNHOFEN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-344', 'ULRICH PIETSCH');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-37', 'VICTOR OEHRN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-371', 'WALDEMAR MEHL');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-767', 'WALTER DANKLEFF');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-118', 'WERNER CZYGAN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-515', 'WERNER HENKE');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-582', 'WERNER SCHULTE');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-256', 'WILHELM BRAUEL');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-431', 'WILHELM DOMMES');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-565', 'WILHELM FRANKEN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-34', 'WILHELM ROLLMANN');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-286', 'WILLI DIETRICH');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-575', 'WOLFGANG BOEHMER');

INSERT INTO UBOATS (UBOAT, COMMANDER) 
VALUES ('U-79', 'WOLFGANG KAUFMANN');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('20-MAR-1941'), 'U-106', '1');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('25-NOV-1941'), 'U-331', '4');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('28-DEC-1939'), 'U-30', '4');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('04-JUL-1943'), 'U-409', '14');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('30-APR-1942'), 'U-456', '16');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('28-NOV-1943'), 'U-407', '19');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('04-DEC-1939'), 'U-31', '28');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('21-NOV-1939'), 'U-21', '35');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('23-OCT-1942'), 'U-161', '43');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('17-SEP-1939'), 'U-29', '50');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('01-SEP-1940'), 'U-32', '58');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('23-JUL-1943'), 'U-407', '59');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('15-DEC-1941'), 'U-557', '71');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('16-JUN-1942'), 'U-205', '74');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('11-MAR-1942'), 'U-565', '93');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('11-AUG-1942'), 'U-73', '94');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('18-FEB-1944'), 'U-410', '97');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('10-OCT-1941'), 'U-126', '102');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('15-JUN-1942'), 'U-431', '119');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('20-FEB-1944'), 'U-230', '305');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('02-MAR-1944'), 'U-744', '324');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('02-AUG-1942'), 'U-66', '339');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('02-AUG-1942'), 'U-66', '342');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('02-MAR-1944'), 'U-744', '362');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('15-AUG-1944'), 'U-741', '404');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('16-FEB-1944'), 'U-230', '418');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('14-OCT-1942'), 'U-221', '508');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('14-OCT-1942'), 'U-221', '509');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('14-OCT-1942'), 'U-221', '519');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('14-OCT-1942'), 'U-221', '522');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('14-OCT-1942'), 'U-221', '523');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('14-OCT-1942'), 'U-221', '532');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('14-OCT-1942'), 'U-221', '537');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('14-OCT-1942'), 'U-221', '547');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('11-OCT-1943'), 'U-616', '553');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('18-APR-1943'), 'U-123', '615');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('14-OCT-1942'), 'U-221', '620');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('30-DEC-1942'), 'U-435', '752');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('30-DEC-1942'), 'U-435', '754');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('20-APR-1941'), 'U-73', '1003');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('20-APR-1941'), 'U-73', '1037');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('25-AUG-1944'), 'U-764', '1074');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('12-JUL-1942'), 'U-582', '1090');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('05-JUL-1943'), 'U-593', '1123');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('05-JUL-1943'), 'U-593', '1129');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('14-OCT-1942'), 'U-221', '2006');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('29-OCT-1942'), 'U-624', '2190');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('29-OCT-1942'), 'U-624', '2192');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('17-JAN-1943'), 'U-268', '2239');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('17-JAN-1943'), 'U-268', '2267');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('27-OCT-1942'), 'U-436', '2281');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('29-OCT-1942'), 'U-624', '2284');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('08-FEB-1943'), 'U-608', '2335');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('09-MAR-1943'), 'U-405', '2341');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('17-JAN-1943'), 'U-268', '2344');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('11-MAR-1943'), 'U-757', '2398');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('08-MAR-1943'), 'U-527', '2480');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('10-OCT-1941'), 'U-331', '18A18');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('12-OCT-1941'), 'U-75', '2A2');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('12-OCT-1941'), 'U-75', '7A7');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('11-MAR-1942'), 'U-701', 'FY107');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('01-SEP-1944'), 'U-482', 'K416');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('13-FEB-1945'), 'U-992', 'K696');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('15-JUN-1942'), 'U-701', 'FY214');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('09-MAR-1942'), 'U-701', 'FY250');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('20-SEP-1943'), 'U-305', 'I81');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('21-DEC-1941'), 'U-751', 'D10');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('15-NOV-1942'), 'U-155', 'D14');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('20-FEB-1944'), 'U-413', 'D25');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('05-JUL-1940'), 'U-34', 'D30');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('15-JAN-1945'), 'U-1172', 'D48');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('30-DEC-1942'), 'U-435', 'D57');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('26-SEP-1942'), 'U-404', 'D72');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('22-AUG-1944'), 'U-354', 'D77');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('24-NOV-1941'), 'U-124', 'D93');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('14-OCT-1941'), 'U-206', 'K122');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('25-DEC-1939'), 'U-22', 'FY127');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('23-FEB-1941'), 'U-107', 'F104');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('26-OCT-1941'), 'U-83', 'F105');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('14-OCT-1940'), 'U-137', 'F18');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('18-AUG-1942'), 'U-214', 'F18');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('12-NOV-1942'), 'U-515', 'F20');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('30-JUN-1942'), 'U-372', 'F25');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('21-OCT-1941'), 'U-123', 'F28');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('03-APR-1941'), 'U-74', 'F29');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('02-DEC-1940'), 'U-99', 'F30');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('26-MAR-1942'), 'U-652', 'F34');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('13-APR-1941'), 'U-108', 'F35');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('12-JAN-1942'), 'U-77', 'F50');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('03-NOV-1940'), 'U-99', 'F51');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('10-AUG-1940'), 'U-56', 'F56');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('06-MAY-1941'), 'U-97', 'F77');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('13-MAY-1941'), 'U-98', 'F94');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('03-MAR-1945'), 'U-1022', 'FY332');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('19-SEP-1942'), 'U-552', 'FY101');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('12-MAY-1942'), 'U-558', 'FY141');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('24-FEB-1945'), 'U-1203', 'FY204');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('24-OCT-1941'), 'U-563', 'G03');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('25-FEB-1944'), 'U-990', 'G23');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('17-JAN-1942'), 'U-454', 'G26');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('18-DEC-1942'), 'U-565', 'G30');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('20-SEP-1942'), 'U-703', 'G33');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('12-NOV-1942'), 'U-515', 'G35');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('25-JAN-1944'), 'U-360', 'G39');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('10-NOV-1942'), 'U-431', 'G44');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('15-NOV-1943'), 'U-453', 'G45');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('17-JAN-1942'), 'U-133', 'G63');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('09-DEC-1942'), 'U-602', 'G93');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('30-MAR-1944'), 'U-223', 'G99');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('21-JAN-1940'), 'U-22', 'H02');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('24-DEC-1943'), 'U-415', 'H06');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('18-FEB-1940'), 'U-23', 'H16');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('11-MAR-1943'), 'U-432', 'H19');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('31-JAN-1942'), 'U-82', 'H46');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('14-SEP-1942'), 'U-91', 'H60');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('11-APR-1943'), 'U-188', 'H64');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('17-DEC-1942'), 'U-211', 'H79');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('18-OCT-1941'), 'U-101', 'H81');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('29-MAY-1940'), 'U-62', 'H89');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('06-JUL-1944'), 'U-218', 'F160');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('21-JUN-1940'), 'U-28', 'X02');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('19-DEC-1941'), 'U-574', 'I73');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('28-DEC-1942'), 'U-617', 'W25');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('27-MAR-1944'), 'U-510', 'J136');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('24-DEC-1944'), 'U-806', 'J174');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('11-OCT-1943'), 'U-371', 'J194');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('22-AUG-1944'), 'U-480', 'J217');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('22-NOV-1943'), 'U-453', 'J24');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('16-APR-1945'), 'U-190', 'J272');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('17-MAR-1945'), 'U-868', 'J52');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('20-SEP-1942'), 'U-435', 'J93');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('21-AUG-1944'), 'U-480', 'K103');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('19-SEP-1941'), 'U-74', 'K115');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('25-NOV-1944'), 'U-1228', 'K136');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('27-JUN-1944'), 'U-988', 'K137');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('22-FEB-1943'), 'U-118', 'K173');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('20-FEB-1945'), 'U-1276', 'K190');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('11-FEB-1942'), 'U-136', 'K198');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('23-SEP-1943'), 'U-666', 'K227');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('08-AUG-1944'), 'U-667', 'K234');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('11-SEP-1942'), 'U-517', 'K244');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('07-JAN-1944'), 'U-305', 'K250');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('20-SEP-1943'), 'U-270', 'K259');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('15-JUN-1944'), 'U-767', 'K261');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('11-DEC-1943'), 'U-223', 'K299');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('15-JUN-1944'), 'U-764', 'K313');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('04-OCT-1944'), 'U-1227', 'K317');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('07-MAY-1944'), 'U-548', 'K329');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('17-OCT-1941'), 'U-553', 'K34');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('22-FEB-1945'), 'U-1004', 'K368');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('29-MAR-1945'), 'U-315', 'K458');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('26-DEC-1944'), 'U-486', 'K462');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('22-AUG-1944'), 'U-354', 'K466');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('06-DEC-1944'), 'U-775', 'K469');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('21-SEP-1943'), 'U-952', 'K47');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('26-DEC-1944'), 'U-486', 'K470');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('01-MAR-1944'), 'U-358', 'K476');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('29-APR-1945'), 'U-286', 'K479');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('25-JUN-1944'), 'U-984', 'K480');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('06-OCT-1942'), 'U-333', 'K49');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('27-APR-1945'), 'U-1105', 'K554');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('10-MAR-1944'), 'U-575', 'K56');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('26-JAN-1945'), 'U-1051', 'K568');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('02-NOV-1944'), 'U-295', 'K569');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('01-NOV-1944'), 'U-483', 'K580');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('12-AUG-1941'), 'U-568', 'K63');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('14-OCT-1944'), 'U-1223', 'K673');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('17-FEB-1945'), 'U-711', 'K80');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('05-FEB-1942'), 'U-136', 'K86');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('24-DEC-1941'), 'U-568', 'K97');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('23-AUG-1941'), 'U-564', 'K98');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('06-SEP-1943'), 'U-617', 'L108');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('07-FEB-1943'), 'U-596', 'L162');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('24-AUG-1940'), 'U-37', 'L28');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('27-NOV-1941'), 'U-559', 'L44');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('11-DEC-1942'), 'U-443', 'L47');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('12-DEC-1943'), 'U-593', 'L56');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('12-JUN-1942'), 'U-77', 'L77');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('15-SEP-1940'), 'U-48', 'L84');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('20-MAR-1942'), 'U-652', 'L85');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('12-DEC-1943'), 'U-593', 'L96');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('14-AUG-1944'), 'U-667', 'L99');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('01-DEC-1942'), 'U-375', 'M70');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('01-FEB-1943'), 'U-617', 'M84');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('10-APR-1940'), 'U-4', 'N24');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('01-AUG-1940'), 'U-34', 'N69');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('14-OCT-1939'), 'U-47', 'OAK08');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('26-AUG-1941'), 'U-652', 'M47');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('08-MAR-1942'), 'U-587', '406');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('30-JAN-1944'), 'U-278', 'R08');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('11-DEC-1944'), 'U-365', 'R62');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('30-OCT-1939'), 'U-59', '458');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('13-NOV-1941'), 'U-81', '91');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('25-JUL-1942'), 'U-201', 'T137');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('07-JAN-1943'), 'U-371', 'T169');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('21-OCT-1943'), 'U-68', 'T204');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('14-JUN-1944'), 'U-547', 'T218');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('08-FEB-1943'), 'U-521', 'T223');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('05-JUL-1944'), 'U-390', 'T367');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('21-OCT-1941'), 'U-79', 'T60');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('18-NOV-1943'), 'U-515', 'U05');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('20-FEB-1944'), 'U-256', 'U08');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('17-FEB-1945'), 'U-968', 'U11');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('20-MAR-1945'), 'U-968', 'U62');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('12-NOV-1942'), 'U-77', 'U81');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('21-AUG-1944'), 'U-344', 'U87');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('29-JUN-1940'), 'U-51', 'X39');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('02-MAY-1945'), 'U-979', 'FY1601');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('31-JAN-1942'), 'U-105', 'Y87');

INSERT INTO ATTACKS (DAY, UBOAT, SID) 
VALUES (TO_DATE('21-DEC-1939'), 'U-21', 'Z05');

COMMIT; 